// flow-typed signature: d041f8e9963b94019f00d043e8ce3d7a
// flow-typed version: <<STUB>>/react-anime_v^0.3.4/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-anime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-anime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-anime/dist/anime' {
  declare module.exports: any;
}

declare module 'react-anime/dist/anime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-anime/dist/anime.js' {
  declare module.exports: $Exports<'react-anime/dist/anime'>;
}
declare module 'react-anime/dist/anime.min.js' {
  declare module.exports: $Exports<'react-anime/dist/anime.min'>;
}
