// flow-typed signature: 517ff27bbdfbf5b44c3c1a76cd6e9764
// flow-typed version: <<STUB>>/react-component-queries_v^2.1.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-component-queries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-component-queries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-component-queries/commonjs/componentQueries' {
  declare module.exports: any;
}

declare module 'react-component-queries/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-component-queries/commonjs/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-component-queries/commonjs/utils/mergeWith' {
  declare module.exports: any;
}

declare module 'react-component-queries/commonjs/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-component-queries/umd/react-component-queries' {
  declare module.exports: any;
}

declare module 'react-component-queries/umd/react-component-queries.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-component-queries/commonjs/componentQueries.js' {
  declare module.exports: $Exports<'react-component-queries/commonjs/componentQueries'>;
}
declare module 'react-component-queries/commonjs/index.js' {
  declare module.exports: $Exports<'react-component-queries/commonjs/index'>;
}
declare module 'react-component-queries/commonjs/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-component-queries/commonjs/utils/getDisplayName'>;
}
declare module 'react-component-queries/commonjs/utils/mergeWith.js' {
  declare module.exports: $Exports<'react-component-queries/commonjs/utils/mergeWith'>;
}
declare module 'react-component-queries/commonjs/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-component-queries/commonjs/utils/shallowEqual'>;
}
declare module 'react-component-queries/umd/react-component-queries.js' {
  declare module.exports: $Exports<'react-component-queries/umd/react-component-queries'>;
}
declare module 'react-component-queries/umd/react-component-queries.min.js' {
  declare module.exports: $Exports<'react-component-queries/umd/react-component-queries.min'>;
}
