// flow-typed signature: 30a27b7818553d2dec8c0e92239ae48b
// flow-typed version: <<STUB>>/typed_v^0.3.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typed/bin/typed.browser' {
  declare module.exports: any;
}

declare module 'typed/bin/typed.browser.min' {
  declare module.exports: any;
}

declare module 'typed/grunt' {
  declare module.exports: any;
}

declare module 'typed/spec/jasmineExtensions' {
  declare module.exports: any;
}

declare module 'typed/spec/typeCheck.spec' {
  declare module.exports: any;
}

declare module 'typed/spec/typed.spec' {
  declare module.exports: any;
}

declare module 'typed/spec/typeParser/commentParser.performance' {
  declare module.exports: any;
}

declare module 'typed/spec/typeParser/commentParser.spec' {
  declare module.exports: any;
}

declare module 'typed/spec/typeParser/suffixParser.spec' {
  declare module.exports: any;
}

declare module 'typed/src/typeCheck' {
  declare module.exports: any;
}

declare module 'typed/src/typed' {
  declare module.exports: any;
}

declare module 'typed/src/typeParser/commentParser' {
  declare module.exports: any;
}

declare module 'typed/src/typeParser/noParser' {
  declare module.exports: any;
}

declare module 'typed/src/typeParser/suffixParser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typed/bin/typed.browser.js' {
  declare module.exports: $Exports<'typed/bin/typed.browser'>;
}
declare module 'typed/bin/typed.browser.min.js' {
  declare module.exports: $Exports<'typed/bin/typed.browser.min'>;
}
declare module 'typed/grunt.js' {
  declare module.exports: $Exports<'typed/grunt'>;
}
declare module 'typed/spec/jasmineExtensions.js' {
  declare module.exports: $Exports<'typed/spec/jasmineExtensions'>;
}
declare module 'typed/spec/typeCheck.spec.js' {
  declare module.exports: $Exports<'typed/spec/typeCheck.spec'>;
}
declare module 'typed/spec/typed.spec.js' {
  declare module.exports: $Exports<'typed/spec/typed.spec'>;
}
declare module 'typed/spec/typeParser/commentParser.performance.js' {
  declare module.exports: $Exports<'typed/spec/typeParser/commentParser.performance'>;
}
declare module 'typed/spec/typeParser/commentParser.spec.js' {
  declare module.exports: $Exports<'typed/spec/typeParser/commentParser.spec'>;
}
declare module 'typed/spec/typeParser/suffixParser.spec.js' {
  declare module.exports: $Exports<'typed/spec/typeParser/suffixParser.spec'>;
}
declare module 'typed/src/typeCheck.js' {
  declare module.exports: $Exports<'typed/src/typeCheck'>;
}
declare module 'typed/src/typed.js' {
  declare module.exports: $Exports<'typed/src/typed'>;
}
declare module 'typed/src/typeParser/commentParser.js' {
  declare module.exports: $Exports<'typed/src/typeParser/commentParser'>;
}
declare module 'typed/src/typeParser/noParser.js' {
  declare module.exports: $Exports<'typed/src/typeParser/noParser'>;
}
declare module 'typed/src/typeParser/suffixParser.js' {
  declare module.exports: $Exports<'typed/src/typeParser/suffixParser'>;
}
